name: gemini
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # network
  http: ^0.13.3
  http_interceptor: ^1.0.2
  dartz: ^0.10.1
  logger: ^1.1.0

  # file
  image_picker: ^1.1.1
  video_player: ^2.8.6
  lottie: ^3.0.0

  # speech
  speech_to_text: ^6.6.1
  flutter_tts: ^4.0.2

  # local db
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # getX
  get: ^4.6.6

  # common
  flutter_linkify: ^6.0.0
  url_launcher: ^6.0.20
  shake: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/animations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf